name: CMake
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            EXTRA_C_FLAGS: -std=c89 --pedantic -Wall -Werror -Wconversion -fsanitize=address -fsanitize=leak --coverage
          - os: macos-latest
            EXTRA_C_FLAGS: -std=c89 --pedantic -Wall -Werror -Wconversion -fsanitize=address --coverage
          - os: windows-latest
            EXTRA_C_FLAGS: /Wall /WX /wd5045 /wd4711 /wd4710
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_FLAGS="${{ matrix.EXTRA_C_FLAGS }}"
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
    
    - name: Generate coverage report
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y lcov
        lcov --capture --directory ${{github.workspace}}/build --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info
    
    - name: Run ApiCov analysis
      if: matrix.os == 'ubuntu-latest'
      uses: codesa-ai/ApiCov@v0.3.25-pre
      with:
        root_path: ${{ github.workspace }}
        install_path: ${{ github.workspace }}/build
        api_key: ${{ secrets.APICOV_KEY_LIBBASE }}
        compile: gcc
        api_source: headers
        headers_dir: ${{ github.workspace }}/include
        
